@startuml

Ecosystem *-- Life
Life <-- Animal
Life <-- Plant
Ecosystem <-- Energy
Energy <-- Meat
Energy <-- OrganicWaste

class Ecosystem {
    x : int
    y : int
    age : int
}

class Life {
    life_points : int
    energy_reserve : int
    gender : String
    age : int
    food_type : String
    vision_zone : Array
    contact_zone : Array
    
    modify_energy()
    modify_life_points()
}

class Animal {
    hierarchy : int
    
    modify_hierarchy()
}

class Plant {
    root_zone : Array
    seeding_zone : Array
}

class Meat {
    age : int
}

class OrganicWaste {
}

abstract class Energy {
    amount : int
}

@enduml